### PR TITLE
STBIDEF STBIRDEF STBIWDEF inline

### PR DESCRIPTION
**Pull request by beru**
Hi, this PR staticinlines `stb_image`, `stb_image_resize`, `stb_image_write`.

### CODE REVIEW

**Comment by nothings** [comment]
1. Inline isn't standard in C before C99, so you can't just turn it on for STB_IMAGE_STATIC etc. (You could version test to see if it's C99 though.)

2. What is the benefit to doing it? For example, in stb_image, the only functions annoted with STBIDEF are the *API* functions, which generally aren't doing a lot, but might be called from multiple places in user code, needlessly expanding the generated code without seeing any performance benefit.

**Comment by beru** [comment]
> 1. Inline isn't standard in C before C99, so you can't just turn it on for STB_IMAGE_STATIC etc. (You could version test to see if it's C99 though.)

Please check the code again, I tweaked preprocessor macros based on your comment.
Maybe a bit ugly....

Some old compilers support inlining with `__inline` or `__inline__`, but those are not supported with this PR. I wish 20th century ghosts won't haunt me...

> 2. What is the benefit to doing it? For example, in stb_image, the only functions annoted with STBIDEF are the API functions, which generally aren't doing a lot, but might be called from multiple places in user code, needlessly expanding the generated code without seeing any performance benefit.

By using `inline` keywords, I can remove `defined but not used [-Wunused-function]` warnings when I use stb library from header-only C++ library.

https://github.com/tiny-dnn/tiny-dnn/pull/685 is related.

**Comment by nothings** [comment]
>By using inline keywords, I can remove defined but not used [-Wunused-function] warnings when I use >stb library from header-only C++ library.

Makes sense. But what about all the functions that aren't STBIDEF? They're not warned about being unused since they're referenced by a static inline function? This feels like a hack that may not work for all time, I suppose there's no better way to turn off the warning locally to that block of code?

**Comment by beru** [comment]
I don't know much about gcc but according to this page.
https://gcc.gnu.org/onlinedocs/gcc-3.4.3/gcc/Warning-Options.html
> -Wunused-function
Warn whenever a static function is declared but not defined or a non\-inline static function is unused. 

So using inline keyword might be the only way to take a hike?
Or stop using `-Wall` or `-Wunused-function` option is less-distressful but people are spartan to hunt bugs.

**Comment by beru** [comment]
> Makes sense. But what about all the functions that aren't STBIDEF? They're not warned about being unused since they're referenced by a static inline function? This feels like a hack that may not work for all time, I suppose there's no better way to turn off the warning locally to that block of code?

Actually, I haven't deeply tried to find other ways to turn off the warnings.

```cpp
#define STB_IMAGE_IMPLEMENTATION
#define STBIDEF inline
#undef STB_IMAGE_STATIC
#include "stb/stb_image.h"
```
This might work...

**Comment by Kerndog73** [comment]
Would declaring every function as `STBI_DEF` and then letting the client set `STBI_DEF` completely break everything?

I'm using stb_image in a header-only C++ library. I had to manually declare every function as inline to get it to work but I would rather the preprocessor do that for me.

    // define functions as inline
    #define STBIDEF inline
    // define globals as static
    #define STB_IMAGE_STATIC
    #define STB_IMAGE_IMPLEMENTATION
    #include "stb_image.h"

**Comment by nothings** [comment]
Letting the client define a STBIDEFPRIVATE or some such might be the best way around this, yeah.

**Comment by nothings** [comment]
In the next release, STB_IMAGE_WRITE supports setting STBIWDEF before you include it. Let me know if this is a workable solution and I'll do it to the others.

**Comment by Kerndog73** [comment]
It looks like defining `STBIWDEF` actually isn't necessary. It would seem that I have forgotten the meaning of `static`. And I call myself a programmer... 

The reason I was getting linker errors the first time around was because **some** of the private functions in image_write aren't `static`. So I just thought, "oh, duplicate symbol, EVERYTHING MUST BE INLINE". When in fact, all I had to do was define `STB_IMAGE_WRITE_STATIC`.

These private functions in stb_image_write are not `static`

- `stbi_zlib_compress`
- `stbi_write_png_to_mem`
- `stbiw__write_run_data`
- `stbiw__write_dump_data`
- `stbiw__write_hdr_scanline`
- `stbiw__linear_to_rgb`

There could be more in the other libraries. It's an easy mistake to make. All you have to do is put this

    #define STB_XXX_STATIC
    #define STB_XXX_IMPLEMENTATION
    #include "stb_xxx.h"

in two separate C files and then link them together and you'll find the rest.

I also just downloaded the latest version of stb_image and found an occurrence of `STBI_REALLOC` being used instead of `STBI_REALLOC_SIZED`. Luckily, there's only two and they're right next to each other. Inside `stbi__load_gif_main` at lines 6526 and 6528.

**Comment by nothings** [comment]
added a compile test and fixed all the non-static functions in stb_image, stb_image_write, and stb_truetype. for next release

**Pull request closed without merging**
