### PR TITLE
Adding memory and assert defines to stb_image_write

### PR DESCRIPTION
**Pull request by callidus**
Adding memory and assert defines to stb_image_write to match stb_image

### CODE REVIEW

**Comment by nothings** [comment]
Note to self: actually it has even been version-bumped. However, still need to do following:
  - tweak credits
  - remove use of memcpy and only use memmove so macro-replacement API is slightly simpler

**Comment by nothings** [comment]
I changed your credit to your full name; if you'd prefer "github:callidus" I'll change it back.

**Comment by nothings** [comment]
Also I renamed all the macros to be STBIW_ rather than assume they should all use the same macros as stb_image.h

**Comment by callidus** [comment]
that makes sense, thank you Sean. Credit how ever you think best, im not fussy. Thanks for such a useful library

**Pull request merged**
