### PR TITLE
Fix 2 pixel to 1 pixel with wrap and fix output buffer for output callback

### PR DESCRIPTION
**Pull request by jeffrbig2**

### CODE REVIEW

**Comment by jeffrbig2** [comment]
Wait, I'm updating the comments...

**Comment by nothings** [comment]
Fixes #1602.

**Comment by nothings** [comment]
Just to be clear, you changed the one function to take `row0` and `row1`, but the only thing you do with `row0` is an assert?

**Comment by jeffrbig2** [comment]
Yes. Eventually, I may use that parameter for other clipping checks...

**Comment by nothings** [comment]
Should it be in an `STBIR__UNUSED()`?

**Comment by jeffrbig2** [comment]
Oh gad, in release mode, you'd get that dumb warning?

**Comment by nothings** [comment]
I haven't seen it, but I assume you'd get it on some compiler with some settings (which we don't control since it's compiled as source with the user's settings).

**Pull request merged**
