### PR TITLE
Misc. comment typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3`

### CODE REVIEW

**Comment by nothings** [comment]
If you back out the changes to deprecated/rrsprintf.h and deprecated/stb_image.c, I'll gladly merge this.

**Comment by luzpaz** [comment]
Done.

**Comment by luzpaz** [comment]
Please merge 
https://github.com/memononen/nanovg/pull/457

**Comment by luzpaz** [comment]
Soft bump

**Comment by nothings** [comment]
Finally merged for next release, thank you for your submission and your patience.

**Pull request closed without merging**
