### PR TITLE
stb_vorbis: allow disabling the seek api

### PR DESCRIPTION
**Pull request by sezero**
Bound to the new STB_VORBIS_NO_SEEK_API define.

### CODE REVIEW

**Comment by nothings** [comment]
what problem does this solve?

**Comment by sezero** [comment]
It helps with users discard code which is dead to them

**Comment by nothings** [comment]
It's not worth doing a feature-by-feature disabling, as it becomes too hard to maintain the code due to all the various combinations of flags.

**Comment by sezero** [comment]
As you wish, feel free to close.

**Pull request closed without merging**
