### PR TITLE
Avoiding conditional directives that break statements

### PR DESCRIPTION
**Pull request by RomeroMalaquias**

### CODE REVIEW

**Comment by nothings** [comment]
why?

**Comment by RomeroMalaquias** [comment]
Hi,
this change is only aesthetical, it's a suggestion based on code style guidelines from the Linux Kernel. 
[Linux kernel coding style](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892)

**Comment by nothings** [comment]
This file isn't part of the linux kernel. I'm not going to randomly apply some rules from random style guides to random stb libraries.

Also, the linked style guide doesn't actually recommend this change.

**Comment by RomeroMalaquias** [comment]
Ok, thanks for your time

**Pull request closed without merging**
