### PR TITLE
add PAM reading to stb_image.h

### PR DESCRIPTION
**Pull request by wesleygriffin**
The PAM format is a generic Netpbm format that can represent PBM/PGM/PPM along with higher channel images.

### CODE REVIEW

**Comment by nothings** [comment]
When you say "represent", do you mean "code the same images", or do you mean "has an identical file format"? Like, should this replace the existing PNM loaders?

**Comment by nothings** [comment]
I see Wikipedia says:

>As of 2015 PAM is not widely accepted or produced by graphics systems; e.g., XnView and FFmpeg support it.

**Comment by wesleygriffin** [comment]
It can code the same images. The header format is different. I do not think it should replace the existing loaders.

Unlike PGM (1 channel) and PPM (3 channel), PAM supports arbitrary channels. I most often use it for 4 channel images.

I might have to edit the Wikipedia page - I see PAM used frequently in academia, its a very simple format that's easy to read and write. My pull request is simply a way to not have to maintain a separate PAM I/O path.

I'm happy to resolve the conflicts if you plan on merging.

Thanks,
Wes

**Comment by nothings** [comment]
The main issue is that stb_image is now getting widely deployed, to the point I suspect people are now using it in places where they *don't* control the image inputs. That means we're trying to be more careful about security in stb_image, which means we're not adding new image formats unless they're extremely popular.

**Comment by wesleygriffin** [comment]
That's a fine argument to not merge. I'm not really interested in trying to ensure the code is safe for uncontrolled inputs.

**Comment by cheako** [comment]
Duplicate of #39

**Pull request closed without merging**
