### PR TITLE
Fix 2 pixel to 1 pixel with wrap and fix output buffer for output callback

### PR DESCRIPTION
**Pull request by jeffrbig2**

### CODE REVIEW

**Comment by nothings** [comment]
Fixes #1602

**Comment by nothings** [comment]
Can you explain why "no double reflect" is testing `> w*3` rather than `> w*2`, when the latter seems to make more sense?

**Comment by jeffrbig2** [comment]
We allow you to reflect 1x off the left, then 1x for the pixel buffer of course, and then 1x on the right.    2x2 with some filters could get off the 1x on the left, so that you would have have wrap a 2nd time (which I just don't support)..
 
  -Jeff

**Comment by jeffrbig2** [comment]
Can walk you through on zoom if helpful...
 
  -Jeff

**Comment by jeffrbig2** [comment]
I guess that's a shitty comment...
 
  -Jeff

**Pull request closed without merging**
