### PR TITLE
fix compiler warnings and const error

### PR DESCRIPTION
**Pull request by ab-cpp**
2 unused parameter warnings and a few parameters that should be 'const'.

### CODE REVIEW

**Comment by nothings** [comment]
Unused parameters need to use STBI_UNUSED in the function body for C compatibility.

write_png const fix is good, but the static function shouldn't get const, it should be cast away in the caller (stb_image convention is no const in internal functions, only on API).

**Comment by ab-cpp** [comment]
Thanks for your feedback ! Requested changes made.

**Comment by nothings** [comment]
Great, thanks for the speedy fix! Merged for next release.

**Comment by nothings** [comment]
(FWIW you put a bunch of C++ -isms in that I had to fix since it has to build as both C and C++, but no big deal.)

**Comment by ab-cpp** [comment]
Aah, thanks, I forgot the C constraint (I guess const_cast<> didn't work so well :)

**Pull request closed without merging**
