### PR TITLE
stretchy_buffer can work with C++ with some macro changes.

### PR DESCRIPTION
**Pull request by TimothyWrightSoftware**
This has been tested on my Widows 10 machine and Ubuntu 14.04.  Please let me know if there are any problems.

### CODE REVIEW

**Comment by DanielGibson** [comment]
The neat thing about the stretchy_buffers.h approach (in contrast to some other dynamic array implementations for C) is that you *don't* have to pass the element type all the time.

Furthermore, having different APIs for C vs C++ makes it pretty useless - IMHO the only usecase to use this in C++ (instead of a proper dynamic array class that makes sure copy/move constructors are called when moving data around etc, like std::vector) I see is C code that should also compile as C++ (like stb-like libs) - obviously that won't work this way.

https://github.com/nothings/stb/issues/250#issuecomment-209904505 has a nice, short solution for the problem without changing the API.

**Comment by nothings** [comment]
I agree with @DanielGibson. @TimothyWrightSoftware, what exactly are you trying to accomplish here, e.g. what's your use case?

**Comment by TimothyWrightSoftware** [comment]
You still don't have to pass the type in if this already works for you, but because this was marked as working with C++ and then changed back to not working with C++, I was curious if it could be done without templates, presumably because anyone using an stb library doesn't like C++

**Comment by TimothyWrightSoftware** [comment]
But I do see your point about having two different API.  I Didn't think about that.

**Comment by DanielGibson** [comment]
> presumably because anyone using an stb library doesn't like C++

well either you use C++ and can live with using a simple templated function or you don't use C++ and then the non-templated version of the function is used, I don't see the problem. Using C++ and insisting on not using templates at all (even in 3rd-party code as an implementation detail) is just silly.

People use stb-libs with C++ all the time, it makes perfect sense: Just because your code is C++ (possibly Orthodox C++) it doesn't mean you insist on all libs you're using being written in C++ (in case of Orthodox C++, they actually prefer C libs to ones using "modern C++" or even just using STL). And of course the alternatives (libpng, libjpeg, ... for stb_image, freetype for stb_truetype, ...) are also plain C, so C++ fans don't lose anything by using stb libs anyway.
You could look at Dear ImGui for an example: It's written in C++ (but doesn't use STL) and uses several stb libs.

**Pull request closed without merging**
