### PR TITLE
Fix for 32bpp bmp images that load with alpha=0 on all pixels

### PR DESCRIPTION
**Pull request by urraka**
I found a case where the loaded image would be incorrectly fully transparent. This seems to fix that.

### CODE REVIEW

**Comment by nothings** [comment]
Fixed in next version (2.08) -- I rewrote the fix to be a bit cleaner/faster, please check if 2.08 is still fixed for you.

**Comment by nothings** [comment]
Er, version 2.07, not 2.08.

**Comment by urraka** [comment]
Works perfectly.

On a side note, I get a compilation error on this line:
`#if defined (STBI_NO_BMP) && (STBI_NO_TGA) && (STBI_NO_GIF)`
https://github.com/nothings/stb/blob/023ff3ffd2d62ed3e4a654001c7a6b0d081dddf2/stb_image.h#L1303

I imagine you meant:
`#if defined(STBI_NO_BMP) && defined(STBI_NO_TGA) && defined(STBI_NO_GIF)`

(this is because I'm defining `STBI_ONLY_PNG` `STBI_ONLY_JPEG` `STBI_ONLY_BMP` `STBI_ONLY_GIF`).

**Comment by nothings** [comment]
Fixed that for next version (that I'll release later today, probably).

**Pull request closed without merging**
