### PR TITLE
stb_perlin: extern stb_perlin_noise3_seed

### PR DESCRIPTION
**Pull request by fluffrabbit**
* Make sure you're using a special branch just for this pull request. (Sometimes people unknowingly use a default branch, then later update that branch, which updates the pull request with the other changes if it hasn't been merged yet.)

Whoops. Anyways, this is needed for doing custom fractal stuff.

### CODE REVIEW

**Comment by fluffrabbit** [comment]
Any reason you're hesitating to merge this?

**Comment by nothings** [comment]
I only process PRs in batches every several months, not as they come in.

**Comment by fluffrabbit** [comment]
Ok. For this one, you changed the file so it might better for you to just add the export yourself and close the PR.

**Comment by nothings** [comment]
git is smart enough to merge it properly.

BTW, it must have semed weird that i changed this file and didn't process your PR, but what happened is I had made a local change to this file like 3 months ago, and since all the libs are in the same repository it was easier to just release that change while I was processing some other things. I didn't fully triage all the open PRs, just tagged them with which lib they were in and only processed the bugs for some libs, not this one.

**Comment by fluffrabbit** [comment]
Magic!

**Pull request merged**
