### PR TITLE
stb_textedit: Support for Page Up/Down

### PR DESCRIPTION
**Pull request by Xipiryon**
I've made some changes in stb_textedit to support Page Up/Down from Dear ImGui (https://github.com/ocornut/imgui/commit/ec945f44)

### CODE REVIEW

**Comment by Xipiryon** [comment]
Just a bit of additional info: this code was tested in the ImGui internal tests suite project (there is a unit test for it) on a resizeable text input widget, by simply moving around the cursor, with and without being in selection mode, from start/middle/end of line/document.

**Comment by ocornut** [comment]
About the tests mentioned above: while it's not something you can repro with raw stb_textedit we ought to mention they existed as it might increase confidence in the validity of this PR.

And we shipped with PageUp/PageDown in the multi-line inputs in early October with no issue reported since.

Here's a GIF and Log of aforementioned test (written by Xipiryon above)

inputtext_pageup_pagedown

```
[0000] -- WindowRef 'Test Window' 00000000
[0001] -- ItemInput 'Field' > 00000000
[0024] OK imgui_tests_widgets.cpp:886 'state != NULL'
[0024] -- KeyPressMap(UpArrow, 1)
[0027] OK imgui_tests_widgets.cpp:915 'stb.cursor [0] == 0 [0]'
[0027] -- KeyPressMap(LeftArrow, 1)
[0030] OK imgui_tests_widgets.cpp:917 'stb.cursor [0] == 0 [0]'
[0030] -- KeyPressMap(DownArrow, 1)
[0033] OK imgui_tests_widgets.cpp:919 'stb.cursor [10] == char_count_per_line [10]'
[0033] -- KeyPressMap(RightArrow, 1)
[0036] OK imgui_tests_widgets.cpp:921 'stb.cursor [1] == 1 [1]'
[0036] -- KeyPressMap(UpArrow, 1)
[0039] OK imgui_tests_widgets.cpp:925 'stb.cursor [9] == cursor_pos_end_of_first_line [9]'
[0039] -- KeyPressMap(LeftArrow, 1)
[0042] OK imgui_tests_widgets.cpp:927 'stb.cursor [8] == cursor_pos_end_of_first_line - 1 [8]'
[0042] -- KeyPressMap(DownArrow, 1)
[0045] OK imgui_tests_widgets.cpp:929 'stb.cursor [19] == cursor_pos_end_of_first_line + char_count_per_line [19]'
[0045] -- KeyPressMap(RightArrow, 1)
[0048] OK imgui_tests_widgets.cpp:931 'stb.cursor [10] == cursor_pos_end_of_first_line + 1 [10]'
[0048] -- KeyPressMap(UpArrow, 1)
[0051] OK imgui_tests_widgets.cpp:935 'stb.cursor [80] == cursor_pos_begin_of_last_line - char_count_per_line [80]'
[0051] -- KeyPressMap(LeftArrow, 1)
[0054] OK imgui_tests_widgets.cpp:937 'stb.cursor [89] == cursor_pos_begin_of_last_line - 1 [89]'
[0054] -- KeyPressMap(DownArrow, 1)
[0057] OK imgui_tests_widgets.cpp:939 'stb.cursor [90] == has_trailing_line_feed ? eof : cursor_pos_begin_of_last_line [90]'
[0057] -- KeyPressMap(RightArrow, 1)
[0060] OK imgui_tests_widgets.cpp:941 'stb.cursor [91] == cursor_pos_begin_of_last_line + 1 [91]'
[0060] -- KeyPressMap(UpArrow, 1)
[0063] -- KeyPressMap(LeftArrow, 1)
[0066] OK imgui_tests_widgets.cpp:947 'stb.cursor [98] == cursor_pos_end_of_last_line - 1 [98]'
[0066] -- KeyPressMap(DownArrow, 1)
[0069] OK imgui_tests_widgets.cpp:949 'stb.cursor [99] == has_trailing_line_feed ? eof : cursor_pos_end_of_last_line [99]'
[0069] -- KeyPressMap(RightArrow, 1)
[0072] OK imgui_tests_widgets.cpp:951 'stb.cursor [99] == cursor_pos_end_of_last_line + (has_trailing_line_feed ? 1 : 0) [99]'
[0072] -- KeyPressMap(UpArrow, 1)
[0075] OK imgui_tests_widgets.cpp:955 'stb.cursor [39] == cursor_pos_middle - char_count_per_line [39]'
[0075] -- KeyPressMap(LeftArrow, 1)
[0078] OK imgui_tests_widgets.cpp:957 'stb.cursor [48] == cursor_pos_middle - 1 [48]'
[0078] -- KeyPressMap(DownArrow, 1)
[0081] OK imgui_tests_widgets.cpp:959 'stb.cursor [59] == cursor_pos_middle + char_count_per_line [59]'
[0081] -- KeyPressMap(RightArrow, 1)
[0084] OK imgui_tests_widgets.cpp:961 'stb.cursor [50] == cursor_pos_middle + 1 [50]'
[0084] -- KeyPressMap(Home, 1)
[0087] OK imgui_tests_widgets.cpp:965 'stb.cursor [40] == ((vars.LineCount / 2) - 1) * char_count_per_line [40]'
[0087] -- KeyPressMap(End, 1)
[0090] OK imgui_tests_widgets.cpp:967 'stb.cursor [49] == (vars.LineCount / 2) * char_count_per_line - 1 [49]'
[0090] -- KeyPressMap(Ctrl+Home, 1)
[0093] OK imgui_tests_widgets.cpp:971 'stb.cursor [0] == 0 [0]'
[0093] -- KeyPressMap(Ctrl+End, 1)
[0096] OK imgui_tests_widgets.cpp:973 'stb.cursor [99] == cursor_pos_end_of_last_line + (has_trailing_line_feed ? 1 : 0) [99]'
[0096] -- KeyPressMap(PageDown, 1)
[0099] OK imgui_tests_widgets.cpp:977 'stb.cursor [40] == cursor_pos_begin_of_first_line + char_count_per_line * page_size [40]'
[0099] -- KeyPressMap(PageUp, 1)
[0102] OK imgui_tests_widgets.cpp:979 'stb.cursor [0] == cursor_pos_begin_of_first_line [0]'
[0102] -- KeyPressMap(PageDown, 1)
[0105] OK imgui_tests_widgets.cpp:983 'stb.cursor [45] == cursor_pos_middle_of_first_line + char_count_per_line * page_size [45]'
[0105] -- KeyPressMap(PageDown, 1)
[0108] OK imgui_tests_widgets.cpp:985 'stb.cursor [85] == cursor_pos_middle_of_first_line + char_count_per_line * page_size * 2 [85]'
[0108] -- KeyPressMap(PageDown, 1)
[0111] OK imgui_tests_widgets.cpp:987 'stb.cursor [95] == has_trailing_line_feed ? eof : eof - (char_count_per_line / 2) + 1 [95]'
[0111] -- KeyPressMap(PageUp, 1)
[0114] OK imgui_tests_widgets.cpp:993 'stb.cursor [55] == cursor_pos_begin_current_line - (page_size * char_count_per_line) + (char_count_per_line / 2) [55]'
[0114] -- KeyCharsAppend('
')
[0121] -- KeyPressMap(UpArrow, 1)
[0124] OK imgui_tests_widgets.cpp:915 'stb.cursor [0] == 0 [0]'
[0124] -- KeyPressMap(LeftArrow, 1)
[0127] OK imgui_tests_widgets.cpp:917 'stb.cursor [0] == 0 [0]'
[0127] -- KeyPressMap(DownArrow, 1)
[0130] OK imgui_tests_widgets.cpp:919 'stb.cursor [10] == char_count_per_line [10]'
[0130] -- KeyPressMap(RightArrow, 1)
[0133] OK imgui_tests_widgets.cpp:921 'stb.cursor [1] == 1 [1]'
[0133] -- KeyPressMap(UpArrow, 1)
[0136] OK imgui_tests_widgets.cpp:925 'stb.cursor [9] == cursor_pos_end_of_first_line [9]'
[0136] -- KeyPressMap(LeftArrow, 1)
[0139] OK imgui_tests_widgets.cpp:927 'stb.cursor [8] == cursor_pos_end_of_first_line - 1 [8]'
[0139] -- KeyPressMap(DownArrow, 1)
[0142] OK imgui_tests_widgets.cpp:929 'stb.cursor [19] == cursor_pos_end_of_first_line + char_count_per_line [19]'
[0142] -- KeyPressMap(RightArrow, 1)
[0145] OK imgui_tests_widgets.cpp:931 'stb.cursor [10] == cursor_pos_end_of_first_line + 1 [10]'
[0145] -- KeyPressMap(UpArrow, 1)
[0148] OK imgui_tests_widgets.cpp:935 'stb.cursor [80] == cursor_pos_begin_of_last_line - char_count_per_line [80]'
[0148] -- KeyPressMap(LeftArrow, 1)
[0151] OK imgui_tests_widgets.cpp:937 'stb.cursor [89] == cursor_pos_begin_of_last_line - 1 [89]'
[0151] -- KeyPressMap(DownArrow, 1)
[0154] OK imgui_tests_widgets.cpp:939 'stb.cursor [100] == has_trailing_line_feed ? eof : cursor_pos_begin_of_last_line [100]'
[0154] -- KeyPressMap(RightArrow, 1)
[0157] OK imgui_tests_widgets.cpp:941 'stb.cursor [91] == cursor_pos_begin_of_last_line + 1 [91]'
[0157] -- KeyPressMap(UpArrow, 1)
[0160] -- KeyPressMap(LeftArrow, 1)
[0163] OK imgui_tests_widgets.cpp:947 'stb.cursor [98] == cursor_pos_end_of_last_line - 1 [98]'
[0163] -- KeyPressMap(DownArrow, 1)
[0166] OK imgui_tests_widgets.cpp:949 'stb.cursor [100] == has_trailing_line_feed ? eof : cursor_pos_end_of_last_line [100]'
[0166] -- KeyPressMap(RightArrow, 1)
[0169] OK imgui_tests_widgets.cpp:951 'stb.cursor [100] == cursor_pos_end_of_last_line + (has_trailing_line_feed ? 1 : 0) [100]'
[0169] -- KeyPressMap(UpArrow, 1)
[0172] OK imgui_tests_widgets.cpp:955 'stb.cursor [39] == cursor_pos_middle - char_count_per_line [39]'
[0172] -- KeyPressMap(LeftArrow, 1)
[0175] OK imgui_tests_widgets.cpp:957 'stb.cursor [48] == cursor_pos_middle - 1 [48]'
[0175] -- KeyPressMap(DownArrow, 1)
[0178] OK imgui_tests_widgets.cpp:959 'stb.cursor [59] == cursor_pos_middle + char_count_per_line [59]'
[0178] -- KeyPressMap(RightArrow, 1)
[0181] OK imgui_tests_widgets.cpp:961 'stb.cursor [50] == cursor_pos_middle + 1 [50]'
[0181] -- KeyPressMap(Home, 1)
[0184] OK imgui_tests_widgets.cpp:965 'stb.cursor [40] == ((vars.LineCount / 2) - 1) * char_count_per_line [40]'
[0184] -- KeyPressMap(End, 1)
[0187] OK imgui_tests_widgets.cpp:967 'stb.cursor [49] == (vars.LineCount / 2) * char_count_per_line - 1 [49]'
[0187] -- KeyPressMap(Ctrl+Home, 1)
[0190] OK imgui_tests_widgets.cpp:971 'stb.cursor [0] == 0 [0]'
[0190] -- KeyPressMap(Ctrl+End, 1)
[0193] OK imgui_tests_widgets.cpp:973 'stb.cursor [100] == cursor_pos_end_of_last_line + (has_trailing_line_feed ? 1 : 0) [100]'
[0193] -- KeyPressMap(PageDown, 1)
[0196] OK imgui_tests_widgets.cpp:977 'stb.cursor [40] == cursor_pos_begin_of_first_line + char_count_per_line * page_size [40]'
[0196] -- KeyPressMap(PageUp, 1)
[0199] OK imgui_tests_widgets.cpp:979 'stb.cursor [0] == cursor_pos_begin_of_first_line [0]'
[0199] -- KeyPressMap(PageDown, 1)
[0202] OK imgui_tests_widgets.cpp:983 'stb.cursor [45] == cursor_pos_middle_of_first_line + char_count_per_line * page_size [45]'
[0202] -- KeyPressMap(PageDown, 1)
[0205] OK imgui_tests_widgets.cpp:985 'stb.cursor [85] == cursor_pos_middle_of_first_line + char_count_per_line * page_size * 2 [85]'
[0205] -- KeyPressMap(PageDown, 1)
[0208] OK imgui_tests_widgets.cpp:987 'stb.cursor [100] == has_trailing_line_feed ? eof : eof - (char_count_per_line / 2) + 1 [100]'
[0208] -- KeyPressMap(PageUp, 1)
[0211] OK imgui_tests_widgets.cpp:993 'stb.cursor [65] == cursor_pos_begin_current_line - (page_size * char_count_per_line) + (char_count_per_line / 2) [65]'
[0229] Success.
```

**Comment by nothings** [comment]
thanks for clarification.

I've just gotten even slower at processing PRs since covid, and I was already slow.

**Comment by ocornut** [comment]
Absolutely no peer pressure on our side, we've been happily running with a few patches for a while and it's not an issue here.
We just felt that adding the extra clarification may be beneficial for the day you can look at them.

Thank you as always <3

**Comment by rygorous** [comment]
LGTM. This is now merged into the dev branch and will be in the next release.

**Pull request closed without merging**
