### PR TITLE
stb_image: fix assert failing when loading BMP

### LINKED ISSUE #897: Assertion `info.offset == (s->img_buffer - s->buffer_start)' failed  for particular .bmp
stb fails to read some .bmp images: 
/stb/stb_image.h:5327: void* stbi__bmp_load(stbi__context*, int*, int*, int*, int, stbi__result_info*): Assertion `info.offset == (s->img_buffer - s->buffer_start)' failed

Code snippet:
```

        int tmpWidth;
        int tmpHeight;
        int tmpChannels;

        using StbImageDataPtr = std::unique_ptr<unsigned char, decltype(&stbi_image_free)>;
        StbImageDataPtr stbData(stbi_load($filePath, &tmpWidth, &tmpHeight, &tmpChannels, 0), &stbi_image_free);
```
Image attached: 
[grace_hopper.zip](https://github.com/nothings/stb/files/4148088/grace_hopper.zip)

### LINKED ISSUE #909: .BMP file crashes when loaded via stbi_load_from_memory(), loads fine via stbi_load() [image attached]
I found a .BMP file which crashes when loaded via `stbi_load_from_memory()` with a failed assertion while it loads fine via `stbi_load()`. This is the code I used for loading from memory:

```
#define STB_IMAGE_IMPLEMENTATION
#include "stb/stb_image.h"

#include <assert.h>

int main(int argc, const char **argv) {
    int w = 0;
    int h = 0;
    int n = 0;
    char *imgencodedfile = NULL;

    FILE *f = fopen("modelpack11/forktruck.bmp", "rb");
    assert(f != NULL);

    fseek(f, 0L, SEEK_END);
    int32_t size = ftell(f);
    fseek(f, 0L, SEEK_SET);
    assert(size > 0);

    imgencodedfile = malloc(size);
    assert(imgencodedfile != NULL);
    int result = fread(imgencodedfile, 1, size, f);
    assert(result == size);

    fclose(f);
    
    unsigned char *data = stbi_load_from_memory(
        (unsigned char *)imgencodedfile, size, &w, &h, &n, 4
    );
    return 0;
}
```

This is the resulting crash:
```
stb/stb_image.h:5327: stbi__bmp_load: Assertion `info.offset == (s->img_buffer - s->buffer_start)' failed.
```

This is the zipped up "modelpack11" folder which contains the affected `modelpack11/forktruck.bmp` image (zipped as a whole to retain the license file, it's someone else's image):

[modelpack11.zip](https://github.com/nothings/stb/files/4210956/modelpack11.zip)

### PR DESCRIPTION
**Pull request by zturtleman**
This fixes two issues with an assert failing. I tested that the first part fixes #909 and the second fixes #897.

A.  Loading 16/24/32-bit BMP from memory caused an assert to fail (excluding 16-bit BMP with `hsz` 12).

`img_buffer` offset was always compared with the buffer for `stbi_load_from_file()` but `stbi_load_from_memory()` uses an external buffer.

Resolution: Change `s->buffer_start` to `s->img_buffer_original`.

B. Loading BMP with large header from file caused assert to fail.

`img_buffer` points to `stbi_uc buffer_start[128]` but the largest BMP supported has a 138 byte header (`hsz` 124) causing `img_buffer` to wrap around to an offset of 10. The assert fails because 138 (header size) != 10 (offset in temp read buffer).

Resolution: Add the previously read bytes to the offset in temp read buffer to get the absolute offset.

Fixes bug introduced in c440a53 ("stb_image: fix reading BMP with explicit masks")

----

The image attached to #909 only triggered the assert when loaded using stbi_load_from_memory() due to small BMP header size. The image attached to #897 triggered the assert in both cases (stbi_load_from_memory() and stbi_load_from_file()).

I personally ran into the issue with a 32-bit BMP exported from GIMP 2.10 which triggered the assert in both cases like #897 . Zipped BMP: [clover.zip](https://github.com/nothings/stb/files/4377932/clover.zip)

### CODE REVIEW

**Comment by nothings** [comment]
Looks good, except your "Fixes: c440a53" doesn't make any sense. I understand it fixes #909 and #897, but I'm not sure what that comment means. Does it fix a bug *introduced* by c440a53?

**Comment by zturtleman** [comment]
Yes, the issues were introduced by that commit. I've change the commit message to say this.

`Fixes: commit-id ("message")` format is used by the Linux kernel, and to a lesser extent Mesa 3D, to mean this commit fixes an issue introduced in the specified commit. I think it's used to help backport bug fixes to stable releases. Anyway, sorry for the confusion.

**Comment by nothings** [comment]
No problem.

**Comment by cxw42** [comment]
I also have a file exhibiting #897, and this PR (at commit e919bcd) fixed the problem for me.  Thanks @zturtleman!

**Comment by halx99** [comment]
It's time to merge this PR?

**Comment by nothings** [comment]
> It's time to merge this PR?

Don't post unhelpful comments.

**Pull request merged**
