### PR TITLE
Added flipping functionality for stb_image_write.h

### PR DESCRIPTION
**Pull request by haikarainen**
See #302 

Please review this code. **Proper testing added!** ~~I have NOT written tests or properly tested all changes as I'm not accustomed to your unit testing methods. I have, however, manually tested it in my project and there it works just fine.~~  

I feel confident to merge this, but it is of course your call @nothings 

The code that is doing the magic is copy-pasted from stb_image.h.

Please be gentle, it has been a while since I worked on a C-project, and I'm still getting used to creating pull requests.
.

### CODE REVIEW

**Comment by haikarainen** [comment]
Currently writing tests, so far png fails, do **not** merge.

**Comment by haikarainen** [comment]
Allright, tests are pushed and working over here. Simply compile with `gcc stbiw_flip_test.c -lm -o stbiw_flip_test` inside the `tests` folder and then just run `./stbiw_flip_test`

**Comment by nothings** [comment]
I know it's much later, but can you explain what this comment means? 

>Please note that this function modifies the data parameter you pass to any 
>of the stb_write functions. Copy it using memcpy or likewise if you want to
>preserve or reuse it later.

**Comment by haikarainen** [comment]
@nothings Sure, take a look at this function for example (stbi_write_png):

https://github.com/nothings/stb/pull/303/commits/45f4eed1078b4968a4fadb5677e7d9feaea1900f#diff-469d4cb48b9965801e6c8cb7b92e46feR1041

It takes a `const void * data` as a parameter, but this is casted to a `void *` and modified inside the function (dirty I know), which means that the raw data you pass to write to an image file will actually be flipped in memory. I know this is somewhat bad practice, and it puts the user of the library as responsible for making a copy of the data before you pass it (if you want to preserve it). It does, however come with the benefit of letting the user skip a datacopy if it's not neccessary.

I can see a few different things you can do to clean this up (change constness of parameter, actually copy the data every time etc), but in the end it's your library (and should probably be your call). 


Disclaimer: It was quite a long time ago I wrote this so I might have missed some detail

**Comment by nothings** [comment]
Ah, it modifies the _pixel_ data, ok. Yeah, I think it would be better to just traverse the input data in reverse while writing it instead, I'll look at changing it work that way.

**Comment by FredGithub** [comment]
Aww, I was so happy to find this until I noticed it's not merged yet! It's okay though :)

**Comment by haikarainen** [comment]
@FredGithub You could always just clone my pull request, unless you need something that has been added later.

**Comment by FredGithub** [comment]
Thanks! I'll take a look

**Comment by andrewcorrigan** [comment]
It'd be really useful if this got merged (without modifying the pixel data)

**Comment by felipeek** [comment]
really helpful, thx :)

**Comment by nothings** [comment]
Added a version of this in the next release, flips w/o modifying input data, all five formats supported, untested.

**Pull request closed without merging**
